# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maintenance_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np

from PyQt5 import QtCore, QtGui, QtWidgets
from Line_class import Line
from Track import Track


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 875)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 610, 241, 171))
        self.label.setObjectName("label")
        self.track_status_selection = QtWidgets.QComboBox(Form)
        self.track_status_selection.setGeometry(QtCore.QRect(90, 620, 104, 26))
        self.track_status_selection.setObjectName("Track_Status_Selection")
        self.line_selection = QtWidgets.QComboBox(Form)
        self.line_selection.setGeometry(QtCore.QRect(40, 650, 104, 26))
        self.line_selection.setObjectName("Line_Selection")
        self.section_selection = QtWidgets.QComboBox(Form)
        self.section_selection.setGeometry(QtCore.QRect(60, 690, 104, 26))
        self.section_selection.setObjectName("Section_Selection")
        self.block_selection = QtWidgets.QSpinBox(Form)
        self.block_selection.setGeometry(QtCore.QRect(60, 720, 104, 26))
        self.block_selection.setObjectName("Block_Selection")
        self.maintenance_signal_output = QtWidgets.QPlainTextEdit(Form)
        self.maintenance_signal_output.setGeometry(QtCore.QRect(130, 750, 104, 26))
        self.maintenance_signal_output.setObjectName("Maintenance_Signal_Selection")
        self.main_button = QtWidgets.QPushButton(Form)
        self.main_button.setGeometry(QtCore.QRect(550, 560, 871, 221))
        self.main_button.setObjectName("Main_button")
        self.maintenance_button = QtWidgets.QPushButton(Form)
        self.maintenance_button.setGeometry(QtCore.QRect(50,570,113,32))
        self.maintenance_button.setObjectName("Maintenance_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.main_button.clicked.connect(lambda:self.closescr(Form))
        track_status = ["Open","Close"]
        red_line = Line("Red")
        green_line = Line("Green")
        lines = [red_line.get_label(),green_line.get_label()]
        section = ["A","B","C"]
        self.maintenance(Form,track_status,lines,section)
        self.maintenance_button.clicked.connect(lambda:self.set_signal(Form))
    
    def closescr(self,Form):
        Form.hide()
    
    def maintenance(self,Form,track_status,lines,section):
        self.track_status_selection.addItems(track_status)
        self.line_selection.addItems(lines)
        self.section_selection.addItems(section)

    def set_signal(self,Form):
        if self.track_status_selection.currentText() == "Open":
            self.maintenance_signal_output.setPlainText("False")
        else:
            self.maintenance_signal_output.setPlainText("True")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "- Track Status: \n"
"\n"
"- Line: \n"
"\n"
"- Section: \n"
"\n"
"- Block #: \n"
"\n"
"- Maintenance Signal:"))
        self.main_button.setText(_translate("Form", "Back to Main Window"))
        self.maintenance_button.setText(_translate("Form", "Maintenance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
