# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 875)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 130, 211, 371))
        self.label.setObjectName("label")
        self.switch_status_selection = QtWidgets.QComboBox(Form)
        self.switch_status_selection.setGeometry(QtCore.QRect(100, 190, 104, 26))
        self.switch_status_selection.setObjectName("switch_status_selection")
        self.track_occupancy_selection = QtWidgets.QComboBox(Form)
        self.track_occupancy_selection.setGeometry(QtCore.QRect(120, 220, 104, 26))
        self.track_occupancy_selection.setObjectName("track_occupancy_selection")
        self.failure_status_selection = QtWidgets.QComboBox(Form)
        self.failure_status_selection.setGeometry(QtCore.QRect(100, 250, 104, 26))
        self.failure_status_selection.setObjectName("failure_status_selection")
        self.ticket_sales_selection = QtWidgets.QComboBox(Form)
        self.ticket_sales_selection.setGeometry(QtCore.QRect(90, 290, 104, 26))
        self.ticket_sales_selection.setObjectName("ticket_sales_selection")
        self.location_selection = QtWidgets.QComboBox(Form)
        self.location_selection.setGeometry(QtCore.QRect(70, 320, 104, 26))
        self.location_selection.setObjectName("location_selection")
        self.light_decision_selection = QtWidgets.QComboBox(Form)
        self.light_decision_selection.setGeometry(QtCore.QRect(100, 380, 104, 26))
        self.light_decision_selection.setObjectName("light_decision_selection")
        self.gate_crossing_decision_selection = QtWidgets.QComboBox(Form)
        self.gate_crossing_decision_selection.setGeometry(QtCore.QRect(160, 420, 104, 26))
        self.gate_crossing_decision_selection.setObjectName("gate_crossing_decision_selection")
        self.line_selection = QtWidgets.QComboBox(Form)
        self.line_selection.setGeometry(QtCore.QRect(40, 450, 104, 26))
        self.line_selection.setObjectName("line_selection")
        self.time_selection = QtWidgets.QTimeEdit(Form)
        self.time_selection.setGeometry(QtCore.QRect(50, 350, 118, 24))
        self.time_selection.setObjectName("time_selection")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(680, 160, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(670, 80, 201, 361))
        self.label_4.setObjectName("label_4")
        self.suggested_speed_output = QtWidgets.QTextEdit(Form)
        self.suggested_speed_output.setGeometry(QtCore.QRect(800, 190, 131, 21))
        self.suggested_speed_output.setObjectName("suggested_speed_output")
        self.forward_authority_output = QtWidgets.QTextEdit(Form)
        self.forward_authority_output.setGeometry(QtCore.QRect(800, 220, 131, 21))
        self.forward_authority_output.setObjectName("forward_authority_output")
        self.backward_authority_output = QtWidgets.QTextEdit(Form)
        self.backward_authority_output.setGeometry(QtCore.QRect(810, 250, 131, 21))
        self.backward_authority_output.setObjectName("backward_authority_output")
        self.throughput_output = QtWidgets.QTextEdit(Form)
        self.throughput_output.setGeometry(QtCore.QRect(760, 280, 131, 21))
        self.throughput_output.setObjectName("throughput_output")
        self.Main_button = QtWidgets.QPushButton(Form)
        self.Main_button.setGeometry(QtCore.QRect(710, 470, 711, 291))
        self.Main_button.setObjectName("Main_button")
        self.Test_Log_button = QtWidgets.QPushButton(Form)
        self.Test_Log_button.setGeometry(QtCore.QRect(0, 470, 711, 291))
        self.Test_Log_button.setObjectName("Test_Log_button")
        self.maintenance_button = QtWidgets.QPushButton(Form)
        self.maintenance_button.setGeometry(QtCore.QRect(50, 90, 113, 32))
        self.maintenance_button.setObjectName("maintenance_button")
        self.maintenance_signal_output = QtWidgets.QTextEdit(Form)
        self.maintenance_signal_output.setGeometry(QtCore.QRect(810, 320, 131, 21))
        self.maintenance_signal_output.setObjectName("maintenance_signal_output")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(60, 160, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 160, 60, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(320, 160, 48, 24))
        self.spinBox_2.setObjectName("spinBox_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "- Train #: \n"
"\n"
"- Block: \n"
" Switch Status: \n"
"\n"
"- Track Occupancy: \n"
"\n"
"- Failure Status: \n"
"\n"
"- Ticket Sales: \n"
"\n"
"- Location: \n"
"\n"
"- Time: \n"
"\n"
"- Light Decision: \n"
"\n"
"- Gate Crossing Decision: \n"
"\n"
"- Line:"))
        self.label_3.setText(_translate("Form", "Outputs"))
        self.label_4.setText(_translate("Form", "- Suggested Speed: \n"
"\n"
"- Forward Authority: \n"
"\n"
"- Backward Authority: \n"
"\n"
"- Throughput: \n"
"\n"
"- Maintenance Signal: "))
        self.Main_button.setText(_translate("Form", "Back to Main Window"))
        self.Test_Log_button.setText(_translate("Form", "Test Log"))
        self.maintenance_button.setText(_translate("Form", "Maintenance"))
        self.label_2.setText(_translate("Form", "Block #: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
