# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Train import Train
from Line_class import Line 
from Station import Station

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 875)
        self.train_selection = QtWidgets.QSpinBox(Form)
        self.train_selection.setGeometry(QtCore.QRect(120, 600, 48, 24))
        self.train_selection.setSpecialValueText("")
        self.train_selection.setMinimum(0)
        self.train_selection.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 590, 141, 201))
        self.label.setObjectName("label")
        self.starting_location_output = QtWidgets.QPlainTextEdit(Form)
        self.starting_location_output.setGeometry(QtCore.QRect(130, 670, 131, 21))
        self.starting_location_output.setPlainText("")
        self.starting_location_output.setObjectName("Starting_Location_Output")
        self.train_button = QtWidgets.QPushButton(Form)
        self.train_button.setGeometry(QtCore.QRect(70, 550, 113, 32))
        self.train_button.setObjectName("Train_button")
        self.throughput_button = QtWidgets.QPushButton(Form)
        self.throughput_button.setGeometry(QtCore.QRect(320, 550, 221, 32))
        self.throughput_button.setObjectName("Throughput_button")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(310, 570, 211, 131))
        self.label_2.setObjectName("label_2")
        self.throughput_output = QtWidgets.QPlainTextEdit(Form)
        self.throughput_output.setGeometry(QtCore.QRect(400, 640, 131, 21))
        self.throughput_output.setPlainText("")
        self.throughput_output.setObjectName("Throughput_Output")
        self.main_button = QtWidgets.QPushButton(Form)
        self.main_button.setGeometry(QtCore.QRect(570, 580, 871, 221))
        self.main_button.setObjectName("Main_button")
        self.current_time_selection = QtWidgets.QTimeEdit(Form)
        self.current_time_selection.setGeometry(QtCore.QRect(1320, 0, 118, 24))
        self.current_time_selection.setObjectName("Current_Time_Selection")
        self.destination_output = QtWidgets.QPlainTextEdit(Form)
        self.destination_output.setGeometry(QtCore.QRect(100, 700, 131, 21))
        self.destination_output.setPlainText("")
        self.destination_output.setObjectName("Destination_Output")
        self.ticket_sales_output = QtWidgets.QPlainTextEdit(Form)
        self.ticket_sales_output.setGeometry(QtCore.QRect(110, 760, 131, 21))
        self.ticket_sales_output.setPlainText("")
        self.ticket_sales_output.setObjectName("Ticket_Sales_Output")
        self.time_output = QtWidgets.QPlainTextEdit(Form)
        self.time_output.setGeometry(QtCore.QRect(120, 730, 118, 24))
        self.time_output.setObjectName("Time_Selection")
        self.line_train_selection = QtWidgets.QComboBox(Form)
        self.line_train_selection.setGeometry(QtCore.QRect(50, 630, 104, 26))
        self.line_train_selection.setObjectName("Line_Train_Selection")
        self.line_throughput_selection = QtWidgets.QComboBox(Form)
        self.line_throughput_selection.setGeometry(QtCore.QRect(350, 610, 104, 26))
        self.line_throughput_selection.setObjectName("Line_Throughput_Selection")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.main_button.clicked.connect(lambda:self.closescr(Form))
        lines = ["Red","Green"]
        self.select_train_line(Form,lines)
        self.train_button.clicked.connect(lambda:self.output_train(Form))
        self.throughput_button.clicked.connect(lambda:self.output_throughput())
    
    def closescr(self,Form):
        Form.hide()

    def select_train_line(self,Form,lines):
        self.line_train_selection.addItems(lines)
        self.line_throughput_selection.addItems(lines)
        
    def output_train(self,Form):
        output_train = Train(id=self.train_selection.value(),line=self.line_train_selection.currentText())
        output_line = Line(self.line_train_selection.currentText())
        self.starting_location_output.setPlainText(output_train.get_start_block())
        self.destination_output.setPlainText(output_train.get_dest_block())
        self.time_output.setPlainText(str(output_train.get_time()))
        self.ticket_sales_output.setPlainText(str(output_line.get_ticket_sales()))

    def output_throughput(self):
        line = Line(self.line_throughput_selection.currentText())
        self.throughput_output.setPlainText(str(line.get_throughput()))

    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "- Train #: \n"
"\n"
"- Line:\n"
"\n"
"- Starting Location: \n"
"\n"
"- Destination: \n"
"\n"
"- Departure Time: \n"
"\n"
"- Ticket Sales: "))
        self.train_button.setText(_translate("Form", "Select Train"))
        self.throughput_button.setText(_translate("Form", "Select Throughput"))
        self.label_2.setText(_translate("Form", "- Line: \n"
"\n"
" - Throughput:"))
        self.main_button.setText(_translate("Form", "Back to Main Window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
